projects:
  subsdeliverymanager:
    schemaPath: amplify/backend/api/subsdeliverymanager/build/schema.graphql
    includes:
      - ./graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ./graphql/APITypes.ts
        docsFilePath: ./graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
